/**
 * Pre-curated wedding presets for auto-populating the DJ queue.
 * Contains approximately 3 hours of songs per category.
 */

export const presets = {
  slowDance: [
    { videoId: '2Vv-BfVoq4g', title: 'Ed Sheeran - Perfect' },
    { videoId: '450p7goxZqg', title: 'John Legend - All of Me' },
    { videoId: 'rtOvBOTyX00', title: 'Christina Perri - A Thousand Years' },
    { videoId: 'vH6nQBuvJvg', title: 'Elvis Presley - Can\'t Help Falling In Love' },
    { videoId: 'S-IKs1y41V4', title: 'Etta James - At Last' },
    { videoId: '08W91CvfeG8', title: 'Adele - Make You Feel My Love' },
    { videoId: 'x-skFgrV59A', title: 'Lonestar - Amazed' },
    { videoId: 'KnP7V6p61as', title: 'Shania Twain - You\'re Still The One' },
    { videoId: '-Bj25BfJ2Jk', title: 'Taylor Swift - Lover' },
    { videoId: 'ShZ90tBJaaM', title: 'Calum Scott - You Are The Reason' },
    { videoId: '0yW7w8F2TVA', title: 'James Arthur - Say You Won\'t Let Go' },
    { videoId: 'bo_efYhYU2A', title: 'Lady Gaga, Bradley Cooper - Shallow' },
    { videoId: '7UoP9ABJXGE', title: 'Dan + Shay - Speechless' },
    { videoId: 'EkHTsc9PU2A', title: 'Jason Mraz - I\'m Yours' },
    { videoId: 'ghZt2XfPyu0', title: 'Train - Marry Me' },
    { videoId: 'lbjZPFBD6hY', title: 'Norah Jones - Come Away With Me' },
    { videoId: 'hwZNL7QVJjE', title: 'Ben E. King - Stand By Me' },
    { videoId: 'GlPlfCy1urI', title: 'Elton John - Your Song' },
    { videoId: 'COiIC3A0ROM', title: 'Al Green - Let\'s Stay Together' },
    { videoId: 'Oi2XzHlsqvY', title: 'Lionel Richie, Diana Ross - Endless Love' },
    { videoId: '3JWTaaS7LdU', title: 'Whitney Houston - I Will Always Love You' },
    { videoId: 'a-Lp2uC_1lg', title: 'Shania Twain - From This Moment On' },
    { videoId: '6IUG-UlpTjaI', title: 'The Temptations - My Girl' },
    { videoId: 'LjhCEhWiKXk', title: 'Bruno Mars - Just the Way You Are' },
    { videoId: 'h9ZGKALMMuc', title: 'Frank Sinatra - The Way You Look Tonight' },
    { videoId: '8-8n-u98rP8', title: 'Rascal Flatts - Bless The Broken Road' },
    { videoId: 'nOidX2D1E1g', title: 'Tim McGraw - My Best Friend' },
    { videoId: 'fV8vB1BB2qc', title: 'Boyz II Men - I\'ll Make Love To You' },
    { videoId: 'vUSzL2leaFM', title: 'Eric Clapton - Wonderful Tonight' },
    { videoId: 'ZGoWtY_h4xo', title: 'Bryan Adams - (Everything I Do) I Do It For You' },
    { videoId: 'P_u9uN8tFpI', title: 'Celine Dion - Because You Loved Me' },
    { videoId: 'WQnAxOQxQIU', title: 'Savage Garden - Truly Madly Deeply' },
    { videoId: 'S_E2EHVxNAE', title: 'Richard Marx - Right Here Waiting' },
    { videoId: 'XjwZAa2EjKA', title: 'Katy Perry - Unconditionally' },
    { videoId: 'unXf8dC7Hk0', title: 'Lukas Graham - Love Someone' },
    { videoId: 'dI4idW_fL68', title: 'Leon Bridges - Beyond' },
    { videoId: 'RPBpS6In0YI', title: 'Haley Reinhart - Can\'t Help Falling in Love' },
    { videoId: 'GemKqzILV4w', title: 'Snow Patrol - Chasing Cars' },
    { videoId: 'AuJrEBtmM1Q', title: 'Ronan Keating - When You Say Nothing At All' },
    { videoId: 'ac3HkriqdGQ', title: 'Lifehouse - You and Me' }
  ],
  lineDance: [
    { videoId: 'hjoZZmVhHqQ', title: 'Cupid Shuffle' },
    { videoId: 'wZv62ShoStY', title: 'Cha Cha Slide' },
    { videoId: 'w1F5Bjjutjc', title: 'Macarena' },
    { videoId: 'q0syIofO_JU', title: 'Wobble' },
    { videoId: 'ltw_f63ZlTo', title: 'Footloose' },
    { videoId: 'd05tQrhNMkA', title: 'Boot Scootin\' Boogie' },
    { videoId: 'mOYZaiDZ7BM', title: 'Cotton Eye Joe' },
    { videoId: 'v7_C59H4SZY', title: 'Electric Slide' },
    { videoId: '84Lc6O96fD4', title: 'Any Man of Mine' },
    { videoId: 'nTwmZp8W6_4', title: 'Watermelon Crawl' },
    { videoId: 'byQIPdHMpjc', title: 'Achy Breaky Heart' },
    { videoId: 'Vw9L_S-XjE8', title: 'YMCA' },
    { videoId: 'PWgvGjAhvIw', title: 'Hey Ya!' },
    { videoId: 'Tl7mXvK-834', title: 'Dance The Night (Dua Lipa)' },
    { videoId: 'uSD4vsh1zGw', title: 'I Gotta Feeling' },
    { videoId: '6JCLY0Rlx6Q', title: 'Shut Up and Dance' },
    { videoId: 'OPf0YbXqDm0', title: 'Uptown Funk' },
    { videoId: 'gGdGFtwCNBE', title: 'Mr. Brightside' },
    { videoId: '1vhFnTjia_I', title: 'Sweet Caroline' },
    { videoId: 'VcjzHMhBtf0', title: 'Don\'t Stop Believin\'' },
    { videoId: 'l482T0yNkeo', title: 'Livin\' on a Prayer' },
    { videoId: 'xFrGuyw1V8s', title: 'Dancing Queen' },
    { videoId: 'nfWlot6h_JM', title: 'Shake It Off' },
    { videoId: 'eH3giaIzONA', title: 'I Wanna Dance With Somebody' },
    { videoId: 'Gs069dndIYk', title: 'September' },
    { videoId: '3GwjfUFyY6M', title: 'Celebration' },
    { videoId: 'ASwge9ud-nI', title: 'Come On Eileen' },
    { videoId: 'eBpYgpF1bqQ', title: 'We Are Family' },
    { videoId: 'I_izvAbhExY', title: 'Stayin\' Alive' },
    { videoId: 'gYk9nK7-v28', title: 'I Will Survive' },
    { videoId: 'PIb6AZdTr-A', title: 'Girls Just Want To Have Fun' },
    { videoId: '79fzeNUqQbQ', title: 'Like A Prayer' },
    { videoId: 'dQw4w9WgXcQ', title: 'Never Gonna Give You Up' },
    { videoId: 'djV11Xbc914', title: 'Take on Me' },
    { videoId: 'y6Sxv-sUYtM', title: 'Happy' },
    { videoId: 'ruj0LzU-J_A', title: 'Can\'t Stop The Feeling' },
    { videoId: 'KQ6zr6kCPj8', title: 'Party Rock Anthem' },
    { videoId: 'MlW7VUZ737w', title: 'Party In The USA' },
    { videoId: '6Zbi0XmGtMw', title: 'Vengaboys - We Like To Party' },
    { videoId: 'EK_LN3XEcnw', title: 'Mambo No. 5' },
    { videoId: 'Jp6j5HJ-Cok', title: 'La Bamba' },
    { videoId: 'KpxG9_G2tWk', title: 'Let\'s Twist Again' },
    { videoId: 'nEjLFpPajDU', title: 'Shout' },
    { videoId: '9SOryJ7ArvM', title: 'Love Shack' },
    { videoId: 'mvCgSqPZ4EM', title: 'Friends in Low Places' },
    { videoId: 'GeUZfOzo6T8', title: 'Country Girl (Shake It For Me)' },
    { videoId: 'JW5UEW2HeBM', title: 'Chattahoochee' },
    { videoId: 'e4ujS1er1r0', title: 'Chicken Fried' },
    { videoId: '2zNSgSzhBfM', title: 'Can\'t Hold Us' }
  ],
  bollywood: [
    { videoId: 'k4yXQkG2s1E', title: 'Kala Chashma' },
    { videoId: 'pXzSRuU_KAE', title: 'London Thumakda' },
    { videoId: 'pq-tE0aP9Qo', title: 'Chaiyya Chaiyya' },
    { videoId: '1zpw8d9Nl6g', title: 'Let\'s Nacho' },
    { videoId: '0zfw_Q7I4bA', title: 'Aankh Marey' },
    { videoId: 'PvO5uY0_30A', title: 'Kar Gayi Chull' },
    { videoId: '8YmYMeM6mP8', title: 'Abhi Toh Party Shuru Hui Hai' },
    { videoId: 'jH1pA_575-M', title: 'Saturday Saturday' },
    { videoId: 'JAtt8_L7v78', title: 'Tune Maari Entriyaan' },
    { videoId: 'mmU9-hK0U-E', title: 'Badtameez Dil' },
    { videoId: 'v8D1M91X2m8', title: 'Gallan Goodiyaan' },
    { videoId: '0iIOY2J3pLo', title: 'Desi Girl' },
    { videoId: 'LGDvVvF9kMk', title: 'Bom Diggy Diggy' },
    { videoId: 'nD_E78eH0eM', title: 'Dil Chori' },
    { videoId: 'jvL8S6YlXoA', title: 'Sweetheart' },
    { videoId: '_A-vM_8C8eI', title: 'Zingaat' },
    { videoId: 'uB7uH2U5B_o', title: 'Ghungroo' },
    { videoId: 'oKsz-qC3sO0', title: 'Makhna' },
    { videoId: 'kd5F7n-G-Jc', title: 'The Breakup Song' },
    { videoId: 'p8nK_XG3wV4', title: 'Bala' },
    { videoId: 'J8vB_m-pD-0', title: 'Laila Main Laila' },
    { videoId: 'b_o8C6z1y7I', title: 'Kamariya' },
    { videoId: 'bMId5m84W08', title: 'Milegi Milegi' },
    { videoId: 'b8hE_b0Zk4Y', title: 'Aao Kabhi Haveli Pe' },
    { videoId: 'Wd2B8OAotU8', title: 'Nashe Si Chadh Gayi' },
    { videoId: '05TA9jHo-L8', title: 'Galti Se Mistake' },
    { videoId: 'xnF9b-A7-Lk', title: 'Sweety Tera Drama' },
    { videoId: 'hYjOZO3A3U4', title: 'Coca Cola' },
    { videoId: 'z_A791M91X2m', title: 'Poster Lagwa Do' },
    { videoId: 'O6v_Q7I4bA8', title: 'Hauli Hauli' },
    { videoId: 'morni_banke', title: 'Morni Banke - Badhaai Ho' },
    { videoId: 'gud_naal_ishq', title: 'Gud Naal Ishq Mitha' },
    { videoId: 'hook_up_song', title: 'Hook Up Song - SOTY 2' },
    { videoId: 'first_class', title: 'First Class - Kalank' },
    { videoId: 'apna_time_aayega', title: 'Apna Time Aayega' },
    { videoId: 'chalti_hai_kya', title: 'Chalti Hai Kya 9 Se 12' },
    { videoId: 'oonchi_hai_building', title: 'Oonchi Hai Building 2.0' },
    { videoId: 'tamma_tamma_again', title: 'Tamma Tamma Again' },
    { videoId: 'badri_ki_dulhania', title: 'Badri Ki Dulhania' },
    { videoId: 'balam_pichkari', title: 'Balam Pichkari' }
  ]
};
